### ISSUE TITLE
Support multiple turtle

### ISSUE THREAD

**Issue by samuel-1184** [datarho/iturtle#27]
Today there is only one turtle in the screen. Would love to have multiple turtles 😄

Investigation for Python Turtle module:

1. The TurtleScreen class defines graphics windows as a playground for the drawing turtles. Its constructor needs a tkinter.Canvas or a ScrolledCanvas as argument. It should be used when turtle is used as part of some application.
2. The function Screen() returns a singleton object of a TurtleScreen subclass. This function should be used when turtle is used as a standalone tool for doing graphics. As a singleton object, inheriting from its class is not possible.

Therefore:

1. We can introduce a basic Screen to represent the widget.
2. If turtle is created without screen instance passed in, let's create a default screen instead. Otherwise, remember the passed in screen.
3. The turtle informs the screen instance for all the drawings.

**Comment by linbendatarho** [comment]
done
