### ISSUE TITLE
speed function improvement

### ISSUE THREAD

**Issue by samuel-1184** [datarho/iturtle#29]
Per https://www.geeksforgeeks.org/turtle-speed-function-in-python/, here is the definition of speed:

The turtle’s speed lies in the range 0-10.

If input is a number greater than 10 or smaller than 0.5, speed is set to 0.

Speedstrings  are mapped to speedvalues in the following way:

* ‘fastest’ :  0
* ‘fast’    :  10
* ‘normal’  :  6
* ‘slow’    :  3
* ‘slowest’ :  1

Speeds from 1 to 10 enforce increasingly faster animation of line drawing and turtle turning.

**Comment by linbendatarho** [comment]
done
