### ISSUE TITLE
Support mode()

### ISSUE THREAD

**Issue by samuel-1184** [datarho/iturtle#30]
Per https://docs.python.org/3/library/turtle.html#turtle.mode, there are two modes supported by turtle lib:

| Mode | Initial turtle heading | positive angles |
| -- | -- | -- |
| “standard” | to the right (east) | counterclockwise |
| “logo” | upward (north) | clockwise |

This also has impact on `heading()` function as well.

**Comment by linbendatarho** [comment]
done
