### ISSUE TITLE
I’ve tried two types of Notebook, but get the error message: Error displaying widget: model not found, how can I fix this?

### ISSUE THREAD

**Issue by anneeeee** [datarho/iturtle#9]
RT

**Comment by linbendatarho** [comment]
Try the lastest version.

**Comment by linbendatarho** [comment]
Please use conda and jupyterlab 3.5

**Comment by samuel-1184** [comment]
Closing this issue as for now. Please open another issue if you cannot get the widget running.

**Comment by samuel-1184** [comment]
Closing this issue as for now. Please open another issue if you cannot get the widget running.
